# --- Portia Repository Sources ---

# --- local filesystem repo ---
local :
   description : Local Live
   uri         : file://${PORTIA_ROOT}/var/lib/portia
   sync        : live
   priority    : 1
   tags        : push

# vi: ts=3
# vim: et
# vile: noti
